############# English navigation ##############

# main menu
[[main]]
name = "Trang chủ"
url = "/"
weight = 1

[[main]]
name = "Giới thiệu"
url = "about/"
weight = 2

[[main]]
name = "Elements"
url = "elements/"
weight = 3

[[main]]
weight = 4
name = "Dự án"
hasChildren = true

[[main]]
parent = "Dự án"
name = "Blog"
url = "blog/"

[[main]]
parent = "Dự án"
name = "Contact"
url = "contact/"

[[main]]
parent = "Dự án"
name = "Authors"
url = "authors/"

[[main]]
parent = "Dự án"
name = "Categories"
url = "categories/"

[[main]]
parent = "Dự án"
name = "404 Page"
url = "404/"


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Elements"
url = "elements/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
