############# English navigation ##############

# main menu
[[main]]
name = "Trang chủ"
url = "/"
weight = 1

[[main]]
name = "Giới thiệu"
url = "about/"
weight = 2

[[main]]
name = "Hoạt động"
url = "activities/"
weight = 3

[[main]]
weight = 4
name = "Dự án"
hasChildren = true

[[main]]
parent = "Dự án"
name = "Thư viện"
url = "libraries/"

[[main]]
parent = "Dự án"
name = "Blog"
url = "blog/"

[[main]]
parent = "Dự án"
name = "STEM"
url = "stem/"

# footer menu
[[footer]]
name = "Giới thiệu"
url = "about/"
weight = 1

[[footer]]
name = "Hoạt động"
url = "activities/"
weight = 2
